import omni.usd
from pxr import Usd

stage = omni.usd.get_context().get_stage()

# First, let's see what's actually under your robot
robot_root = "/World/nova_carter_empty"
robot_prim = stage.GetPrimAtPath(robot_root)

print("=== Robot Structure ===")
if robot_prim:
    def print_hierarchy(prim, indent=0):
        print("  " * indent + prim.GetPath().pathString)
        for child in prim.GetChildren():
            print_hierarchy(child, indent + 1)
    
    print_hierarchy(robot_prim)
else:
    print(f"Robot root not found at {robot_root}")
    print("Available roots:")
    for prim in stage.GetPseudoRoot().GetChildren():
        print(f"  - {prim.GetPath().pathString}")
        
'''
Expected Output:

=== Robot Structure ===
/World/nova_carter_empty
  /World/nova_carter_empty/Looks
    /World/nova_carter_empty/Looks/Mine_Shaft
      /World/nova_carter_empty/Looks/Mine_Shaft/Shader
    /World/nova_carter_empty/Looks/Selective_Yellow
      /World/nova_carter_empty/Looks/Selective_Yellow/Shader
    /World/nova_carter_empty/Looks/Red
      /World/nova_carter_empty/Looks/Red/Shader
    /World/nova_carter_empty/Looks/Trinidad
      /World/nova_carter_empty/Looks/Trinidad/Shader
    /World/nova_carter_empty/Looks/Pattens_Blue
      /World/nova_carter_empty/Looks/Pattens_Blue/Shader
    /World/nova_carter_empty/Looks/Silver
      /World/nova_carter_empty/Looks/Silver/Shader
    /World/nova_carter_empty/Looks/Boulder
      /World/nova_carter_empty/Looks/Boulder/Shader
    /World/nova_carter_empty/Looks/Black
      /World/nova_carter_empty/Looks/Black/Shader
    /World/nova_carter_empty/Looks/Wild_Sand
      /World/nova_carter_empty/Looks/Wild_Sand/Shader
    /World/nova_carter_empty/Looks/Royal_Blue
      /World/nova_carter_empty/Looks/Royal_Blue/Shader
    /World/nova_carter_empty/Looks/Rajah
      /World/nova_carter_empty/Looks/Rajah/Shader
    /World/nova_carter_empty/Looks/Cape_Cod
      /World/nova_carter_empty/Looks/Cape_Cod/Shader
    /World/nova_carter_empty/Looks/Ivory
      /World/nova_carter_empty/Looks/Ivory/Shader
    /World/nova_carter_empty/Looks/Silver_Chalice
      /World/nova_carter_empty/Looks/Silver_Chalice/Shader
    /World/nova_carter_empty/Looks/Blush_Pink
      /World/nova_carter_empty/Looks/Blush_Pink/Shader
    /World/nova_carter_empty/Looks/Charade
      /World/nova_carter_empty/Looks/Charade/Shader
    /World/nova_carter_empty/Looks/Amber
      /World/nova_carter_empty/Looks/Amber/Shader
    /World/nova_carter_empty/Looks/Blue_Zodiac
      /World/nova_carter_empty/Looks/Blue_Zodiac/Shader
    /World/nova_carter_empty/Looks/Yellow
      /World/nova_carter_empty/Looks/Yellow/Shader
    /World/nova_carter_empty/Looks/Alabaster
      /World/nova_carter_empty/Looks/Alabaster/Shader
    /World/nova_carter_empty/Looks/Gray_Nurse
      /World/nova_carter_empty/Looks/Gray_Nurse/Shader
    /World/nova_carter_empty/Looks/San_Marino
      /World/nova_carter_empty/Looks/San_Marino/Shader
    /World/nova_carter_empty/Looks/Black_Russian
      /World/nova_carter_empty/Looks/Black_Russian/Shader
    /World/nova_carter_empty/Looks/Japonica
      /World/nova_carter_empty/Looks/Japonica/Shader
    /World/nova_carter_empty/Looks/Cadet_Blue
      /World/nova_carter_empty/Looks/Cadet_Blue/Shader
    /World/nova_carter_empty/Looks/Rangoon_Green
      /World/nova_carter_empty/Looks/Rangoon_Green/Shader
    /World/nova_carter_empty/Looks/Jaguar
      /World/nova_carter_empty/Looks/Jaguar/Shader
    /World/nova_carter_empty/Looks/Pizazz
      /World/nova_carter_empty/Looks/Pizazz/Shader
    /World/nova_carter_empty/Looks/Gray
      /World/nova_carter_empty/Looks/Gray/Shader
    /World/nova_carter_empty/Looks/Cornflower
      /World/nova_carter_empty/Looks/Cornflower/Shader
    /World/nova_carter_empty/Looks/Shady_Lady
      /World/nova_carter_empty/Looks/Shady_Lady/Shader
    /World/nova_carter_empty/Looks/Cerulean
      /World/nova_carter_empty/Looks/Cerulean/Shader
    /World/nova_carter_empty/Looks/Hurricane
      /World/nova_carter_empty/Looks/Hurricane/Shader
    /World/nova_carter_empty/Looks/Celeste
      /World/nova_carter_empty/Looks/Celeste/Shader
    /World/nova_carter_empty/Looks/Kabul
      /World/nova_carter_empty/Looks/Kabul/Shader
    /World/nova_carter_empty/Looks/Vulcan
      /World/nova_carter_empty/Looks/Vulcan/Shader
    /World/nova_carter_empty/Looks/Satin_Linen
      /World/nova_carter_empty/Looks/Satin_Linen/Shader
    /World/nova_carter_empty/Looks/Gull_Gray
      /World/nova_carter_empty/Looks/Gull_Gray/Shader
    /World/nova_carter_empty/Looks/Taupe_Gray
      /World/nova_carter_empty/Looks/Taupe_Gray/Shader
    /World/nova_carter_empty/Looks/Shark
      /World/nova_carter_empty/Looks/Shark/Shader
    /World/nova_carter_empty/Looks/Harvest_Gold
      /World/nova_carter_empty/Looks/Harvest_Gold/Shader
    /World/nova_carter_empty/Looks/Como
      /World/nova_carter_empty/Looks/Como/Shader
    /World/nova_carter_empty/Looks/Nobel
      /World/nova_carter_empty/Looks/Nobel/Shader
    /World/nova_carter_empty/Looks/Maroon
      /World/nova_carter_empty/Looks/Maroon/Shader
    /World/nova_carter_empty/Looks/Nugget
      /World/nova_carter_empty/Looks/Nugget/Shader
    /World/nova_carter_empty/Looks/Screaming_Green
      /World/nova_carter_empty/Looks/Screaming_Green/Shader
    /World/nova_carter_empty/Looks/Aquamarine
      /World/nova_carter_empty/Looks/Aquamarine/Shader
    /World/nova_carter_empty/Looks/Mountain_Mist
      /World/nova_carter_empty/Looks/Mountain_Mist/Shader
    /World/nova_carter_empty/Looks/Green
      /World/nova_carter_empty/Looks/Green/Shader
    /World/nova_carter_empty/Looks/Neon_Carrot
      /World/nova_carter_empty/Looks/Neon_Carrot/Shader
    /World/nova_carter_empty/Looks/French_Lilac
      /World/nova_carter_empty/Looks/French_Lilac/Shader
    /World/nova_carter_empty/Looks/Fog
      /World/nova_carter_empty/Looks/Fog/Shader
    /World/nova_carter_empty/Looks/Melrose
      /World/nova_carter_empty/Looks/Melrose/Shader
    /World/nova_carter_empty/Looks/Perano
      /World/nova_carter_empty/Looks/Perano/Shader
    /World/nova_carter_empty/Looks/Bondi_Blue
      /World/nova_carter_empty/Looks/Bondi_Blue/Shader
    /World/nova_carter_empty/Looks/Emperor
      /World/nova_carter_empty/Looks/Emperor/Shader
    /World/nova_carter_empty/Looks/Tangerine
      /World/nova_carter_empty/Looks/Tangerine/Shader
    /World/nova_carter_empty/Looks/Periwinkle_Gray
      /World/nova_carter_empty/Looks/Periwinkle_Gray/Shader
    /World/nova_carter_empty/Looks/Dawn
      /World/nova_carter_empty/Looks/Dawn/Shader
    /World/nova_carter_empty/Looks/Shalimar
      /World/nova_carter_empty/Looks/Shalimar/Shader
    /World/nova_carter_empty/Looks/Bitter_Lemon
      /World/nova_carter_empty/Looks/Bitter_Lemon/Shader
    /World/nova_carter_empty/Looks/Fire_Bush
      /World/nova_carter_empty/Looks/Fire_Bush/Shader
    /World/nova_carter_empty/Looks/Cararra
      /World/nova_carter_empty/Looks/Cararra/Shader
    /World/nova_carter_empty/Looks/Gravel
      /World/nova_carter_empty/Looks/Gravel/Shader
    /World/nova_carter_empty/Looks/Ironside_Gray
      /World/nova_carter_empty/Looks/Ironside_Gray/Shader
    /World/nova_carter_empty/Looks/Mystic
      /World/nova_carter_empty/Looks/Mystic/Shader
    /World/nova_carter_empty/Looks/Almond
      /World/nova_carter_empty/Looks/Almond/Shader
    /World/nova_carter_empty/Looks/Saffron
      /World/nova_carter_empty/Looks/Saffron/Shader
    /World/nova_carter_empty/Looks/Tropical_Blue
      /World/nova_carter_empty/Looks/Tropical_Blue/Shader
    /World/nova_carter_empty/Looks/Mercury
      /World/nova_carter_empty/Looks/Mercury/Shader
    /World/nova_carter_empty/Looks/De_York
      /World/nova_carter_empty/Looks/De_York/Shader
    /World/nova_carter_empty/Looks/Fuchsia_Pink
      /World/nova_carter_empty/Looks/Fuchsia_Pink/Shader
    /World/nova_carter_empty/Looks/Concord
      /World/nova_carter_empty/Looks/Concord/Shader
    /World/nova_carter_empty/Looks/Silver_Rust
      /World/nova_carter_empty/Looks/Silver_Rust/Shader
    /World/nova_carter_empty/Looks/Link_Water
      /World/nova_carter_empty/Looks/Link_Water/Shader
    /World/nova_carter_empty/Looks/Gallery
      /World/nova_carter_empty/Looks/Gallery/Shader
    /World/nova_carter_empty/Looks/Dolly
      /World/nova_carter_empty/Looks/Dolly/Shader
    /World/nova_carter_empty/Looks/Iron
      /World/nova_carter_empty/Looks/Iron/Shader
    /World/nova_carter_empty/Looks/Gold
      /World/nova_carter_empty/Looks/Gold/Shader
    /World/nova_carter_empty/Looks/Midnight_Blue
      /World/nova_carter_empty/Looks/Midnight_Blue/Shader
    /World/nova_carter_empty/Looks/Cloud
      /World/nova_carter_empty/Looks/Cloud/Shader
    /World/nova_carter_empty/Looks/Blue
      /World/nova_carter_empty/Looks/Blue/Shader
    /World/nova_carter_empty/Looks/Tuatara
      /World/nova_carter_empty/Looks/Tuatara/Shader
    /World/nova_carter_empty/Looks/Tidal
      /World/nova_carter_empty/Looks/Tidal/Shader
    /World/nova_carter_empty/Looks/Chicago
      /World/nova_carter_empty/Looks/Chicago/Shader
    /World/nova_carter_empty/Looks/Star_Dust
      /World/nova_carter_empty/Looks/Star_Dust/Shader
    /World/nova_carter_empty/Looks/Milano_Red
      /World/nova_carter_empty/Looks/Milano_Red/Shader
    /World/nova_carter_empty/Looks/Spring_Wood
      /World/nova_carter_empty/Looks/Spring_Wood/Shader
    /World/nova_carter_empty/Looks/Apple
      /World/nova_carter_empty/Looks/Apple/Shader
    /World/nova_carter_empty/Looks/Gamboge
      /World/nova_carter_empty/Looks/Gamboge/Shader
    /World/nova_carter_empty/Looks/Tory_Blue
      /World/nova_carter_empty/Looks/Tory_Blue/Shader
    /World/nova_carter_empty/Looks/Antique_Bronze
      /World/nova_carter_empty/Looks/Antique_Bronze/Shader
    /World/nova_carter_empty/Looks/Tapa
      /World/nova_carter_empty/Looks/Tapa/Shader
    /World/nova_carter_empty/Looks/La_Palma
      /World/nova_carter_empty/Looks/La_Palma/Shader
    /World/nova_carter_empty/Looks/Matisse
      /World/nova_carter_empty/Looks/Matisse/Shader
    /World/nova_carter_empty/Looks/backtire_m
      /World/nova_carter_empty/Looks/backtire_m/backtire_m
    /World/nova_carter_empty/Looks/logo_NVIDIA
      /World/nova_carter_empty/Looks/logo_NVIDIA/logo_NVIDIA
    /World/nova_carter_empty/Looks/lidar_glass_v2_m
      /World/nova_carter_empty/Looks/lidar_glass_v2_m/Shader
    /World/nova_carter_empty/Looks/White
      /World/nova_carter_empty/Looks/White/Shader
  /World/nova_carter_empty/chassis_link
    /World/nova_carter_empty/chassis_link/visual
    /World/nova_carter_empty/chassis_link/front_camera
    /World/nova_carter_empty/chassis_link/Realsense
      /World/nova_carter_empty/chassis_link/Realsense/RSD455
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_Pseudo_Depth
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_Pseudo_Depth/OmniverseKitViewportCameraMesh
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_Pseudo_Depth/OmniverseKitViewportCameraMesh/CameraMode
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Imu_Sensor
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/OmniGlass
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/OmniGlass/Shader
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/Aluminum_Anodized
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/Aluminum_Anodized/Shader
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/Aluminum_Cast
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/Aluminum_Cast/Shader
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/Plastic_ABS
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/Plastic_ABS/Shader
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/OmniPBR
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Looks/OmniPBR/Shader
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/Case_front
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/Glass
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/Case_back
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/USB_C
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/Mount
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/Camera_module
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/Front_mask
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Visual/camera_mask
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Color
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Color/OmniverseKitViewportCameraMesh
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Color/OmniverseKitViewportCameraMesh/CameraMode
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Left
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Left/OmniverseKitViewportCameraMesh
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Left/OmniverseKitViewportCameraMesh/CameraMode
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Right
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Right/OmniverseKitViewportCameraMesh
            /World/nova_carter_empty/chassis_link/Realsense/RSD455/Camera_OmniVision_OV9782_Right/OmniverseKitViewportCameraMesh/CameraMode
        /World/nova_carter_empty/chassis_link/Realsense/RSD455/TemplateRenderProducts
          /World/nova_carter_empty/chassis_link/Realsense/RSD455/TemplateRenderProducts/Camera_Pseudo_Depth_render_product
  /World/nova_carter_empty/wheel_left
    /World/nova_carter_empty/wheel_left/visual
  /World/nova_carter_empty/wheel_right
    /World/nova_carter_empty/wheel_right/visual
  /World/nova_carter_empty/caster_frame_base
    /World/nova_carter_empty/caster_frame_base/visual
  /World/nova_carter_empty/caster_swivel_left
    /World/nova_carter_empty/caster_swivel_left/visual
  /World/nova_carter_empty/caster_swivel_right
    /World/nova_carter_empty/caster_swivel_right/visual
  /World/nova_carter_empty/caster_wheel_left
    /World/nova_carter_empty/caster_wheel_left/visual
  /World/nova_carter_empty/caster_wheel_right
    /World/nova_carter_empty/caster_wheel_right/visual
'''
